// Call Sheet Render Layer
// Pure UI rendering functions extracted from callsheet.js
// Depends on: callsheet state (callSheet, callSheetSettings, csSortCriteria, etc.)
//            callsheet-categories.js (getCategoryDisplayName, getCategoryColor)
//            storage.js, utils.js, dom-helpers.js, tendencies.js

// ============ CONSTANTS (replicated from callsheet.js) ============

// Centralized category color palette (mirrors CSS --cat-* tokens)
const CS_COLORS = {
  red: "#dc3545",
  yellow: "#ffc107",
  orange: "#fd7e14",
  green: "#28a745",
  blue: "#007bff",
  purple: "#6f42c1",
  teal: "#17a2b8",
  gray: "#6c757d",
};

// Call sheet categories with colors and filters - FRONT PAGE
const CALLSHEET_FRONT = [
  // Row 1
  {
    id: "2nd-medium",
    name: "2nd Down Medium (4-6)",
    color: CS_COLORS.red,
    down: "2",
    distance: "Medium",
    position: null,
  },
  {
    id: "2nd-long",
    name: "2nd and Long (7+)",
    color: CS_COLORS.red,
    down: "2",
    distance: "Long",
    position: null,
  },
  {
    id: "3rd-short-1-3",
    name: "3rd and Short (1-3)",
    color: CS_COLORS.yellow,
    down: "3",
    distance: "Short",
    situation: "Short Yardage",
    position: null,
  },
  {
    id: "short-yardage",
    name: "Short Yardage",
    color: CS_COLORS.orange,
    situation: "Short Yardage",
    position: null,
  },
  {
    id: "gbot",
    name: '"G-B-O-T"',
    color: CS_COLORS.purple,
    situation: null,
    position: null,
    manual: true,
  },
  {
    id: "3rd-short-2down",
    name: "3rd and Short (2 Down)",
    color: CS_COLORS.yellow,
    down: "3",
    distance: "Short",
    situation: "Short Yardage",
    position: null,
  },
  {
    id: "rz-20",
    name: "Red Zone +20",
    color: CS_COLORS.green,
    situation: null,
    position: "Green",
  },
  {
    id: "4th-down",
    name: "4th Down",
    color: CS_COLORS.purple,
    down: "4",
    distance: null,
    position: null,
  },
  {
    id: "3rd-medium",
    name: "3rd and Medium (4-7)",
    color: CS_COLORS.yellow,
    down: "3",
    distance: "Medium",
    position: null,
  },
  {
    id: "rz-10",
    name: "Red Zone +10",
    color: CS_COLORS.green,
    situation: null,
    position: "Lo-RZ",
  },
  {
    id: "4-minute",
    name: "4 Minute",
    color: CS_COLORS.yellow,
    situation: "4 Minute",
    position: null,
  },
  {
    id: "3rd-long",
    name: "3rd and Long (7+)",
    color: CS_COLORS.yellow,
    down: "3",
    distance: "Long",
    position: null,
  },
  {
    id: "rz-5",
    name: "Red Zone +5",
    color: CS_COLORS.green,
    situation: null,
    position: "Hi-RZ",
  },
  {
    id: "2-minute",
    name: "2 Minute",
    color: CS_COLORS.yellow,
    situation: "2 Minute",
    position: null,
  },
  {
    id: "backed-up",
    name: "Backed Up",
    color: CS_COLORS.gray,
    situation: null,
    position: "Backed Up",
  },
  {
    id: "goal-line",
    name: "Goal Line (3 and In)",
    color: CS_COLORS.orange,
    situation: "Short Yardage",
    position: "Goal Line",
  },
  {
    id: "last-plays",
    name: "LAST PLAYS",
    color: CS_COLORS.red,
    situation: null,
    position: null,
    manual: true,
  },
  {
    id: "saigon",
    name: "SAIGON",
    color: CS_COLORS.gray,
    situation: null,
    position: "Saigon",
  },
  {
    id: "must-haves",
    name: "MUST HAVES AND FUN",
    color: CS_COLORS.teal,
    situation: null,
    position: null,
    manual: true,
  },
];

// Call sheet categories - BACK PAGE (play types & player-specific)
const CALLSHEET_BACK = [
  // Column 1: Play Types
  {
    id: "openers",
    name: "Openers",
    color: CS_COLORS.green,
    playType: "Opener",
    manual: false,
  },
  {
    id: "1st-down",
    name: "1st Down",
    color: CS_COLORS.yellow,
    down: "1",
    distance: null,
    position: null,
  },
  {
    id: "perimeter-screens",
    name: "Perimeter Screens",
    color: CS_COLORS.teal,
    playType: "Screen",
    manual: false,
  },
  {
    id: "screen",
    name: "Screen",
    color: CS_COLORS.teal,
    playType: "Screen",
    manual: false,
  },
  {
    id: "p-and-10",
    name: "P and 10",
    color: CS_COLORS.yellow,
    situation: null,
    position: null,
    manual: false,
  },
  {
    id: "2-point",
    name: "2 Point Plays",
    color: CS_COLORS.green,
    situation: null,
    position: null,
    manual: true,
  },
  {
    id: "base-run",
    name: "Base run",
    color: CS_COLORS.green,
    playType: "Run",
    manual: false,
  },
  {
    id: "run-options",
    name: "Run Options",
    color: CS_COLORS.green,
    playType: "Run Option",
    manual: false,
  },
  {
    id: "base-pass",
    name: "Base Pass",
    color: CS_COLORS.yellow,
    playType: "Pass",
    manual: false,
  },
  {
    id: "quick",
    name: "Quick",
    color: CS_COLORS.yellow,
    playType: "Quick",
    manual: false,
  },
  {
    id: "play-action",
    name: "Play Action",
    color: CS_COLORS.teal,
    playType: "Play Action",
    manual: false,
  },
  {
    id: "rpos",
    name: "RPOs",
    color: CS_COLORS.orange,
    playType: "RPO",
    manual: false,
  },
  {
    id: "player1",
    name: "Lucas",
    color: CS_COLORS.yellow,
    playerSpecific: true,
    manual: true,
  },
  {
    id: "player2",
    name: "Marco",
    color: CS_COLORS.green,
    playerSpecific: true,
    manual: true,
  },
  {
    id: "player3",
    name: "Diego",
    color: CS_COLORS.orange,
    playerSpecific: true,
    manual: true,
  },
  {
    id: "player4",
    name: "Danny",
    color: CS_COLORS.teal,
    playerSpecific: true,
    manual: true,
  },
  {
    id: "player5",
    name: "Jovani",
    color: CS_COLORS.green,
    playerSpecific: true,
    manual: true,
  },
  {
    id: "movement",
    name: "Movement Passes",
    color: CS_COLORS.purple,
    playType: "Movement",
    manual: false,
  },
];

// Combined categories for reference
const CALLSHEET_CATEGORIES = [...CALLSHEET_FRONT, ...CALLSHEET_BACK];

// Immutable snapshots used by rebuildCallSheetCategoryRegistry as the base source
const BASE_CALLSHEET_FRONT = CALLSHEET_FRONT.slice();
const BASE_CALLSHEET_BACK = CALLSHEET_BACK.slice();

const CS_SEVEN_ON_SEVEN_CATEGORIES = [
  {
    id: "cs-7on7-openers",
    name: "Openers",
    color: CS_COLORS.green,
    manual: false,
    target: 5,
    note: "First calls for the tournament script.",
    criteria: { situation: ["opener"] },
  },
  {
    id: "cs-7on7-first-down",
    name: "1st Down",
    color: CS_COLORS.yellow,
    manual: false,
    target: 5,
    note: "Early-down calls that keep the full menu open.",
    criteria: { down: ["1"] },
  },
  {
    id: "cs-7on7-second-down",
    name: "2nd Down",
    color: CS_COLORS.red,
    manual: false,
    target: 5,
    note: "Best calls for staying on schedule.",
    criteria: { down: ["2"] },
  },
  {
    id: "cs-7on7-third-down",
    name: "3rd Down",
    color: CS_COLORS.yellow,
    manual: false,
    target: 5,
    note: "Short and medium conversion calls.",
    criteria: { down: ["3"], distance: ["short", "medium"] },
  },
  {
    id: "cs-7on7-third-long",
    name: "3rd & Long",
    color: CS_COLORS.orange,
    manual: false,
    target: 4,
    note: "Long-yardage conversion calls.",
    criteria: { down: ["3"], distance: ["long"] },
  },
  {
    id: "cs-7on7-marco",
    name: "Marco",
    color: CS_COLORS.green,
    manual: false,
    target: 3,
    note: "Designed touches and matchup calls for Marco.",
    criteria: { keyPlayer: "Marco" },
  },
  {
    id: "cs-7on7-diego",
    name: "Diego",
    color: CS_COLORS.orange,
    manual: false,
    target: 3,
    note: "Designed touches and matchup calls for Diego.",
    criteria: { keyPlayer: "Diego" },
  },
  {
    id: "cs-7on7-jayce",
    name: "Jayce",
    color: CS_COLORS.teal,
    manual: false,
    target: 3,
    note: "Designed touches and matchup calls for Jayce.",
    criteria: { keyPlayer: "Jayce" },
  },
  {
    id: "cs-7on7-jake",
    name: "Jake",
    color: CS_COLORS.purple,
    manual: false,
    target: 3,
    note: "Designed touches and matchup calls for Jake.",
    criteria: { keyPlayer: "Jake" },
  },
  {
    id: "cs-7on7-skro-bros",
    name: "Skro Bros",
    color: CS_COLORS.blue,
    manual: false,
    target: 3,
    note: "Designed touches and matchup calls for the Skro Bros.",
    criteria: { keyPlayer: "Skro Bros" },
  },
  {
    id: "cs-7on7-running-back",
    name: "Running Back",
    color: CS_COLORS.gray,
    manual: false,
    target: 3,
    note: "Backfield releases, checkdowns, swings, and matchups.",
    criteria: { keyPlayer: "Running Back" },
  },
  {
    id: "cs-7on7-cover-01",
    name: "Cov 0/1 Beaters",
    color: CS_COLORS.red,
    manual: false,
    target: 4,
    note: "Pressure-man and single-high man answers.",
    criteria: { coverage: ["cover 0", "cover 1"] },
  },
  {
    id: "cs-7on7-cover-2",
    name: "Cov 2 Beaters",
    color: CS_COLORS.blue,
    manual: false,
    target: 4,
    note: "Two-high and Cover 2 answers.",
    criteria: { coverage: ["cover 2"] },
  },
  {
    id: "cs-7on7-cover-3",
    name: "Cov 3 Beaters",
    color: CS_COLORS.teal,
    manual: false,
    target: 4,
    note: "Three-deep and Cover 3 answers.",
    criteria: { coverage: ["cover 3"] },
  },
  {
    id: "cs-7on7-man-2",
    name: "Man 2 Beaters",
    color: CS_COLORS.purple,
    manual: false,
    target: 4,
    note: "Two-man and man-under answers.",
    criteria: { coverage: ["2-man"] },
  },
  {
    id: "cs-7on7-shots",
    name: "Shot Plays",
    color: CS_COLORS.red,
    manual: false,
    target: 4,
    note: "Explosives and deliberate downfield calls.",
    criteria: { keyword: "shot | explosive" },
  },
  {
    id: "cs-7on7-wristband-passes",
    name: "Pass Plays on Wristband",
    color: CS_COLORS.teal,
    manual: true,
    target: 0,
    note: "Auto-syncs passing calls whenever a wristband is loaded.",
  },
  {
    id: "cs-7on7-goal-line",
    name: "Goal Line",
    color: CS_COLORS.orange,
    manual: false,
    target: 4,
    note: "Calls for the goal line and compressed field.",
    criteria: { fieldPosition: ["goal line"] },
  },
  {
    id: "cs-7on7-two-point",
    name: "Two-Point Conversion",
    color: CS_COLORS.green,
    manual: false,
    target: 4,
    note: "Must-have two-point calls.",
    criteria: { keyword: "2 point | 2-point | two point | two-point" },
  },
];

const CALLSHEET_DISPLAY_IDS = [
  "callsheetShowNumbers",
  "callsheetShowPersonnel",
  "callsheetShowFormation",
  "callsheetShowFormationTags",
  "callsheetShowBack",
  "callsheetShowOneWordOnly",
  "callsheetShowProtection",
  "callsheetShowPlayName",
  "callsheetShowTags",
  "callsheetShowMotion",
  "callsheetShowLineCall",
  "callsheetShowEmoji",
  "callsheetUseSquares",
  "callsheetUnderEmoji",
  "callsheetBoldShifts",
  "callsheetRedShifts",
  "callsheetItalicMotions",
  "callsheetRedMotions",
  "callsheetRemoveVowels",
  "callsheetHighlightHuddle",
  "callsheetHighlightCandy",
  "callsheetRedBorder",
  "callsheetBlueBorder",
  "callsheetGreenBorder",
  "callsheetOrangeBorder",
  "callsheetPurpleBorder",
  "callsheetPersonnelBorder",
  "callsheetPersonnelBorderColor",
];

const CALLSHEET_DISPLAY_DEFAULTS = {
  callsheetShowBack: true,
};

const CALLSHEET_CELL_DISPLAY_OVERRIDE_PROPS = [
  "cellUseOneWord",
  "cellDisableOneWord",
  "cellForceUnderCenter",
  "cellHidePersonnel",
  "cellHideWristband",
  "cellHideFormation",
  "cellHideFormationTags",
  "cellHideBack",
  "cellHideShift",
  "cellHideMotion",
  "cellHideProtection",
  "cellHidePlayName",
  "cellHidePlayTags",
  "cellHideLineCall",
];

const CALLSHEET_HIGHLIGHT_SWATCHES = [
  { key: "", name: "None", bg: "", border: "", css: "#f8f8f8" },
  { key: "yellow", name: "Yellow", bg: "#fff59d", border: "#d4b106", css: "#fff59d" },
  { key: "lime", name: "Lime", bg: "#dced8b", border: "#8aa51b", css: "#dced8b" },
  { key: "cyan", name: "Cyan", bg: "#b2ebf2", border: "#1f8ea0", css: "#b2ebf2" },
  { key: "pink", name: "Pink", bg: "#f8bbd0", border: "#c04b73", css: "#f8bbd0" },
  { key: "orange", name: "Orange", bg: "#ffe0b2", border: "#c97a19", css: "#ffe0b2" },
];

const CALLSHEET_CELL_DISPLAY_PRESETS = [
  {
    id: "default",
    label: "Reset",
    sublabel: "Use the global display settings for this cell.",
    overrides: {},
  },
  {
    id: "scout",
    label: "Scout",
    sublabel: "Strip tags and extra detail but keep the main call readable.",
    overrides: {
      cellHideWristband: true,
      cellHideFormationTags: true,
      cellHideBack: true,
      cellHideProtection: true,
      cellHidePlayTags: true,
      cellHideLineCall: true,
    },
  },
  {
    id: "ultra-tight",
    label: "Ultra Tight",
    sublabel: "Keep only the essential call pieces for dense sheets.",
    overrides: {
      cellHideWristband: true,
      cellHidePersonnel: true,
      cellHideFormationTags: true,
      cellHideBack: true,
      cellHideShift: true,
      cellHideMotion: true,
      cellHideProtection: true,
      cellHidePlayTags: true,
      cellHideLineCall: true,
    },
  },
  {
    id: "one-word",
    label: "One Word",
    sublabel: "Show only the one-word call in royal blue when available.",
    requiresOneWord: true,
    overrides: {
      cellUseOneWord: true,
    },
  },
];

const CALLSHEET_CELL_DISPLAY_COLORS = {
  cellUseOneWord: { bg: "#4169E1", text: "white" },
  cellDisableOneWord: { bg: "#d9534f", text: "white" },
  cellForceUnderCenter: { bg: "#5cb85c", text: "white" },
  cellHidePersonnel: { bg: "#f0ad4e", text: "#333" },
  cellHideWristband: { bg: "#5bc0de", text: "#333" },
};

// Built-in presets, print defaults, sort fields, and render scheduling are
// owned by callsheet.js. Keep this render split focused on shared category/
// display constants and rendering helpers.
