name = "bcoffense"
pages_build_output_dir = "."
compatibility_date = "2026-05-17"

[[kv_namespaces]]
binding = "SYNC_KV"
id = "aa7a47d6139544bc9bb2aef6622c8bb2"

[[r2_buckets]]
binding = "CLIPS"
bucket_name = "bcoffense-clips"

# D1 relational database — OMG Phase 3
[[d1_databases]]
binding = "DB"
database_name = "bcoffense-db"
database_id = "5def1774-55ad-4c92-afed-5b1f7f199f26"
