import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const render = await readFile(new URL("js/callsheet-render.js", `file://${root}/`), "utf8");
const print = await readFile(new URL("js/callsheet-print.js", `file://${root}/`), "utf8");
const css = await readFile(new URL("css/callsheet.css", `file://${root}/`), "utf8");
const callSheet = await readFile(new URL("js/callsheet.js", `file://${root}/`), "utf8");
const gamePlanRender = await readFile(new URL("js/gameplan-render.js", `file://${root}/`), "utf8");
const notifications = await readFile(new URL("js/app-notifications.js", `file://${root}/`), "utf8");
const indexCards = await readFile(new URL("js/callsheet-index-cards.js", `file://${root}/`), "utf8");
const appEvents = await readFile(new URL("js/app-events.js", `file://${root}/`), "utf8");
const scriptIntegrations = await readFile(new URL("js/script-integrations.js", `file://${root}/`), "utf8");
const gamePlanIntegrations = await readFile(new URL("js/gameplan-integrations.js", `file://${root}/`), "utf8");

assert.match(render, /const wristbandHtml = displayOptions\.showNumbers[\s\S]*?cs-wristband-number[\s\S]*?\$\{wristbandHtml\}[\s\S]*?\$\{personnelHtml\}/, "screen rows render wristband number before personnel and call text");
assert.match(print, /const wristbandHtml = displayOptions\.showNumbers[\s\S]*?print-wristband-number[\s\S]*?\$\{wristbandHtml\}\$\{personnelHtml\}/, "print rows preserve wristband-first order");
assert.match(render, /cs-one-word-call[\s\S]*?cs-one-word-full-call[\s\S]*?\(\$\{fullPlayName\}\)/, "one-word calls retain the full play name in parentheses");
assert.match(css, /\.print-wristband-number \{[\s\S]*?background: transparent !important;[\s\S]*?color: #111827 !important;/, "printed wristband numbers remain visible without printed backgrounds");
assert.match(callSheet, /function getCallSheetLoadedWristbandSummary\(\)[\s\S]*?loaded: Boolean\(name && plays\.length\)/, "loaded wristband state has one persisted source of truth");
assert.doesNotMatch(callSheet, /getElementById\("loadedWristbandDisplay"\)/, "source status and Finalize never scrape wristband state from rendered text");
assert.match(render, /const wristbandNumber = play\.wristbandNumber \|\| \([\s\S]*?getWristbandNumberForPlay\(play\)/, "Personnel page resolves wristband numbers from the loaded wristband mapping");
assert.match(render, /function getCallSheetPersonnelGamePlanPlays\(\)[\s\S]*?_gpEnsureBoard\(\)/, "Personnel page reads the active Game Plan board, not the master playbook");
assert.match(render, /const gamePlanPlays = getCallSheetPersonnelGamePlanPlays\(\)/, "Personnel renderer is scoped to current Game Plan plays");
assert.match(render, /buildCallSheetPersonnelColumns\(personnelGroups\)/, "Personnel packages are balanced into ordered columns");
assert.match(print, /if \(mode === "all"\) return \["front", "back", "personnel"\]/, "three-page jobs include the Personnel sheet after Front and Back");
assert.match(print, /safePage === "personnel"[\s\S]*?renderPersonnelCallSheet\(opts\.printOptions\)/, "Personnel print uses the same classified play renderer as the screen");
assert.match(gamePlanRender, /id="gpLibrarySearch"[\s\S]*?placeholder="Search library…"/, "Game Plan library always exposes its search field");
assert.match(notifications, /const matchIndex = plays\.findIndex[\s\S]*?openPlayWorkflowPanel\(matchIndex\)/, "staff question notifications resolve a play then open its workflow panel by index");
assert.match(indexCards, /data-action="openCallSheetPlayPicker"[\s\S]*?data-drop="csHashDrop"/, "index-card buckets accept the normal Call Sheet drag/drop and picker pipeline");
assert.match(indexCards, /const addControl = editable[\s\S]*?cs-index-bucket-actions[\s\S]*?\$\{addControl\}/, "index-card add-play control stays in the editor header rather than consuming printable bucket height");
assert.match(indexCards, /function openCallSheetIndexCardBucketPicker\(id\)[\s\S]*?_csIndexPickerBucketId = bucket\.id[\s\S]*?openCallSheetPlayPicker/, "Index Card add-play buttons retain their specific bucket destination");
assert.match(indexCards, /function onCallSheetIndexCardPickerPlayAdded\(play\)[\s\S]*?bucket\.playKeys\.push\(identity\)[\s\S]*?saveCallSheetSettings\(\)/, "new picker calls are persisted in smart Index Card bucket scopes");
assert.match(indexCards, /const seen = new Set\(\);[\s\S]*?seen\.has\(identity\)/, "scoped Index Card buckets render one row per play identity even if the source Call Sheet has duplicates");
assert.match(indexCards, /function resolveCallSheetIndexCardPickerPlay\(play, categoryId, hash\)[\s\S]*?find\(\(candidate\)/, "Index Card picker additions re-use an existing canonical call when available");
assert.match(await readFile(new URL("js/callsheet-picker-runtime.js", `file://${root}/`), "utf8"), /onCallSheetIndexCardPickerPlayAdded\(play, editingCategory, editingHash\)/, "the shared Call Sheet picker reports a selection to the active Index Card bucket");
assert.match(await readFile(new URL("js/callsheet-picker-runtime.js", `file://${root}/`), "utf8"), /const selectedPlay = existing \|\| play;[\s\S]*?if \(!existing\) callSheet\[editingCategory\]\[editingHash\]\.push\(play\)/, "the shared picker does not append a duplicate when an Index Card selection already exists");
assert.match(await readFile(new URL("js/callsheet-picker-runtime.js", `file://${root}/`), "utf8"), /let _csPickerSelectionInFlight = false;[\s\S]*?_csPickerSelectionInFlight = true;/, "one picker selection is claimed before it can mutate the Call Sheet");
assert.match(indexCards, /showPlayContextMenu\([\s\S]*?row\.dataset\.category[\s\S]*?row\.dataset\.hash/, "index-card play actions open the canonical Call Sheet cell editor");
assert.match(indexCards, /toggleCallSheetIndexFamily[\s\S]*?toggleCallSheetIndexCompact/, "index cards retain per-row family indentation and repeated-component controls");
assert.match(indexCards, /function openCallSheetIndexCardPrintModal\(\)[\s\S]*?Cards[\s\S]*?Sides[\s\S]*?Copies[\s\S]*?Preview/, "index cards use a dedicated print suite with card, side, copy, and preview controls");
assert.match(indexCards, /function previewCurrentCallSheetIndexCard\(\)[\s\S]*?cards: "current", sides: _csIndexSide, copies: 1/, "Index Card editor has a one-click preview for the active side without changing saved print options");
assert.match(indexCards, /openCallSheetIndexCardPrintModal\(\)[\s\S]*?requestAnimationFrame\(\(\) => overlay\.classList\.add\("visible"\)\)/, "index-card print options use the normal visible modal lifecycle");
assert.match(indexCards, /_runCallSheetIndexCardsPrint[\s\S]*?requestAnimationFrame\(\(\) => requestAnimationFrame/, "index-card printing waits for its isolated print root to paint before opening the browser dialog");
assert.match(indexCards, /function _csIndexPrintSides[\s\S]*?\["front", "back"\][\s\S]*?function renderCallSheetIndexCardPrintPages/, "index-card duplex jobs render front then back for each card");
assert.match(indexCards, /function _runCallSheetIndexCardsPrint[\s\S]*?setupPrintPageStyle[\s\S]*?@page \{ size: 4in 6in/, "index cards use the shared print-page setup with an exact 4×6 page");
assert.match(indexCards, /function _csBucketRows\(bucket\)[\s\S]*?bucket\?\.playKeys[\s\S]*?_csIndexIdentity/, "smart index-card buckets stay scoped to their source calls");
assert.match(indexCards, /function _csSmartIndexPlan\(entries\)[\s\S]*?typeof entry\.play === "object"[\s\S]*?CS_INDEX_SMART_CATEGORY_PRIORITY[\s\S]*?three per side/, "smart index cards preserve direct Script plays and wrapped Game Plan plays while balancing logical groups");
assert.match(indexCards, /function createSmartCallSheetIndexCard\(entries, options = \{\}\)[\s\S]*?saveCallSheet\(\)[\s\S]*?switchCallSheetPage\("index"\)/, "smart generation saves calls then opens the editable index-card workspace");
assert.match(indexCards, /function renameCallSheetIndexCard\(\)/, "index cards support renaming the active card in place");
assert.match(indexCards, /cs-index-card-title-input[\s\S]*?data-onchange="setCallSheetIndexCardTitle"/, "the visible Index Card title can be edited in place");
assert.match(indexCards, /function toggleCallSheetIndexCardHeader\(\)[\s\S]*?card\.hideHeader/, "Index Card title bands can be removed to reclaim printable space");
assert.match(indexCards, /function moveCallSheetIndexBucket\(arg\)/, "index-card situations can be manually reordered");
assert.match(indexCards, /function setCallSheetIndexBucketColor\(id\)/, "index-card situations support their own visible header color");
assert.match(indexCards, /function manageCallSheetIndexCardBucket\(id\)/, "each index-card situation has one complete management surface");
assert.match(indexCards, /excludedPlayKeys/, "index-card buckets can hide individual calls without deleting their canonical Call Sheet source");
assert.match(indexCards, /function removeCallSheetIndexPlay\(arg\)/, "each index-card call can be removed from that compact bucket only");
assert.match(indexCards, /openLoadWristbandModal/, "index-card editing can load or replace the Call Sheet wristband directly");
assert.match(indexCards, /cs-index-wristband-number/, "index-card and print calls show loaded wristband numbers");
assert.match(indexCards, /function _csUpdateIndexCardFitStatus\(\)/, "index-card editing reports whether the live card fits its 4×6 print area");
assert.match(css, /\.cs-index-card \{ box-sizing: border-box; display: flex; flex-direction: column; width: min\(100%, 480px\); height:/, "index-card editing uses a fixed 4×6-proportional frame instead of growing with content");
assert.match(css, /\.cs-index-grid \{ display: grid;[\s\S]*?flex: 1 1 auto; min-height: 0;[\s\S]*?overflow: auto/, "index-card bucket content stays in a constrained scroll region instead of painting over the next situation");
assert.match(css, /\.cs-index-play-actions \{ display: inline-flex; position: absolute;[\s\S]*?pointer-events: none/, "editor-only play controls overlay on demand instead of changing the 4×6 capacity");
assert.match(render, /Index Cards are a fixed physical preview[\s\S]*?card\.scrollIntoView/, "opening Index Cards resets the old Call Sheet scroll position instead of landing mid-card");
assert.match(css, /\.cs-index-print-preview-pages \.cs-index-card \{ width: min\(100%, 390px\); height: auto;[\s\S]*?aspect-ratio: 2 \/ 3/, "index-card preview overrides the editor height and keeps the real 4×6 ratio");
assert.match(scriptIntegrations, /function sendScriptToIndexCallSheet\(\)[\s\S]*?createSmartCallSheetIndexCard/, "Script can build a smart index card from selected or full script plays");
assert.match(gamePlanIntegrations, /function sendGamePlanToIndexCallSheet\(\)[\s\S]*?sourceBoxId[\s\S]*?createSmartCallSheetIndexCard/, "Game Plan can build a smart index card while retaining bucket context");
assert.match(appEvents, /"openCallSheetIndexPlayMenu"/, "delegated event routing passes the index-card play action its source element");
console.log("call sheet call clarity contract: wristband-first and one-word full-call passed");
