// functions/clips/manifest.js — Play video clip manifest API (Cloudflare R2 + KV)
//   GET    /clips/manifest?sig=<playSig>            → list clips for a play (any authed role)
//   POST   /clips/manifest?sig=<playSig>            → upload a clip (admin/coach only)
//   DELETE /clips/manifest?sig=<playSig>&id=<id>    → delete a clip (admin/coach only)
//
// Blobs live in the CLIPS R2 bucket. New writes use an exact, team-scoped
// immutable key; older `clips/<uuid>` objects are recovery evidence. A
// per-play manifest is stored in SYNC_KV under a team-scoped key, with a
// primary-team legacy fallback during the transition.

import { authJson } from "../_lib/auth.js";
import { getMediaAccess, getStaffWriteAccess } from "../_lib/media-access.js";
import { readTeamClipManifest, writeTeamClipManifest } from "../_lib/team-workspace.js";

const MAX_CLIP_BYTES = 25 * 1024 * 1024; // 25 MiB hard cap per clip
const MAX_CLIPS_PER_PLAY = 3;
const MAX_SIG_LENGTH = 400;
const MAX_LABEL_LENGTH = 120;

function getClipBucket(env) {
  return env && env.CLIPS;
}

function requireClipBucket(env) {
  const bucket = getClipBucket(env);
  if (!bucket) throw new Error("Clip storage (R2) is not configured.");
  return bucket;
}

function getManifestStore(env) {
  const store = env && env.SYNC_KV;
  if (!store) throw new Error("Clip manifest storage (KV) is not configured.");
  return store;
}

function normalizeSig(value) {
  return String(value || "").trim();
}

function isValidSig(sig) {
  return Boolean(sig) && sig.length <= MAX_SIG_LENGTH;
}

function isReplaceOnlySig(sig) {
  return String(sig || "").trim().startsWith("signals/");
}

function canonicalClipR2Key(teamId, id) {
  return `media/teams/${encodeURIComponent(String(teamId || "").trim())}/clips/${encodeURIComponent(String(id || "").trim())}`;
}

/**
 * R2 deletion is intentionally narrower than manifest mutation. Historic
 * clip entries used `clips/<id>` (or no r2key at all), and those binaries are
 * retained as recovery evidence even after a team-scoped manifest supersedes
 * them. Only a key generated by this exact writer for this exact team/entry
 * may be garbage-collected.
 */
function isCurrentCanonicalClipEntry(entry, teamId) {
  const id = String(entry?.id || "").trim();
  const r2key = String(entry?.r2key || "").trim();
  return Boolean(id && r2key && r2key === canonicalClipR2Key(teamId, id));
}

async function deleteSupersededCanonicalClipObjects(bucket, teamId, entries, activeEntries = []) {
  const activeKeys = new Set((Array.isArray(activeEntries) ? activeEntries : [])
    .map((entry) => String(entry?.r2key || "").trim())
    .filter(Boolean));
  const keys = [...new Set((Array.isArray(entries) ? entries : [])
    .filter((entry) => isCurrentCanonicalClipEntry(entry, teamId))
    .filter((entry) => !activeKeys.has(entry.r2key))
    .map((entry) => entry.r2key))];
  if (!keys.length) return;
  // The manifest update is the commit point. A failed delete leaves a safe
  // orphan for recovery; it must never make an active manifest point at a
  // missing object.
  await Promise.allSettled(keys.map((key) => bucket.delete(key)));
}

async function readManifest(store, env, teamId, sig) {
  return readTeamClipManifest(store, env, teamId, sig);
}

function publicClip(entry) {
  return {
    id: entry.id,
    label: entry.label || "",
    contentType: entry.contentType || "video/mp4",
    size: entry.size || 0,
    duration: entry.duration || 0,
    uploadedAt: entry.uploadedAt || "",
    uploadedBy: entry.uploadedBy || "",
  };
}

function decodeLabel(raw) {
  if (!raw) return "";
  let value = String(raw);
  try {
    value = decodeURIComponent(value);
  } catch (_err) {
    /* keep raw on malformed encoding */
  }
  return value.replace(/[\r\n\t]+/g, " ").trim().slice(0, MAX_LABEL_LENGTH);
}

async function listClips(context) {
  const url = new URL(context.request.url);
  const sig = normalizeSig(url.searchParams.get("sig"));
  if (!isValidSig(sig)) {
    return authJson({ ok: false, error: "A valid play signature is required." }, { status: 400 });
  }
  const access = await getMediaAccess(context.request, context.env, "clip", sig);
  if (!access.ok) return authJson({ ok: false, error: access.error }, { status: access.status });
  const store = getManifestStore(context.env);
  const { entries } = await readManifest(store, context.env, access.teamId, sig);
  return authJson({ ok: true, clips: entries.map(publicClip) });
}

async function uploadClip(context) {
  const access = await getStaffWriteAccess(context.request, context.env);
  if (!access.ok) return authJson({ ok: false, error: access.error }, { status: access.status });

  const url = new URL(context.request.url);
  const sig = normalizeSig(url.searchParams.get("sig"));
  if (!isValidSig(sig)) {
    return authJson({ ok: false, error: "A valid play signature is required." }, { status: 400 });
  }

  const contentType = (context.request.headers.get("Content-Type") || "").split(";")[0].trim();
  if (!contentType.startsWith("video/")) {
    return authJson({ ok: false, error: "Clip must be a video file." }, { status: 415 });
  }

  const contentLength = Number(context.request.headers.get("Content-Length") || 0);
  if (contentLength > MAX_CLIP_BYTES) {
    return authJson(
      { ok: false, error: "Clip is larger than the 25 MiB limit." },
      { status: 413 },
    );
  }

  const buffer = await context.request.arrayBuffer();
  if (!buffer.byteLength) {
    return authJson({ ok: false, error: "Clip file is empty." }, { status: 400 });
  }
  if (buffer.byteLength > MAX_CLIP_BYTES) {
    return authJson(
      { ok: false, error: "Clip is larger than the 25 MiB limit." },
      { status: 413 },
    );
  }

  const store = getManifestStore(context.env);
  const { entries, legacy: legacyManifest } = await readManifest(store, context.env, access.teamId, sig);
  const replaceExisting = isReplaceOnlySig(sig);
  if (!replaceExisting && entries.length >= MAX_CLIPS_PER_PLAY) {
    return authJson(
      { ok: false, error: `This play already has the maximum of ${MAX_CLIPS_PER_PLAY} clips.` },
      { status: 409 },
    );
  }

  const bucket = requireClipBucket(context.env);
  const id = crypto.randomUUID();
  const r2key = canonicalClipR2Key(access.teamId, id);
  const label = decodeLabel(context.request.headers.get("X-Clip-Label"));
  const durationHeader = Number(context.request.headers.get("X-Clip-Duration") || 0);

  await bucket.put(r2key, buffer, {
    httpMetadata: { contentType },
  });

  const entry = {
    id,
    r2key,
    label,
    contentType,
    size: buffer.byteLength,
    duration: Number.isFinite(durationHeader) && durationHeader > 0 ? Math.round(durationHeader) : 0,
    uploadedAt: new Date().toISOString(),
    uploadedBy: access.session.username,
  };
  await writeTeamClipManifest(store, access.teamId, sig, replaceExisting ? [entry] : [...entries, entry]);

  if (replaceExisting && entries.length && !legacyManifest) {
    await deleteSupersededCanonicalClipObjects(bucket, access.teamId, entries, [entry]);
  }

  return authJson({ ok: true, clip: publicClip(entry) });
}

async function deleteClip(context) {
  const access = await getStaffWriteAccess(context.request, context.env);
  if (!access.ok) return authJson({ ok: false, error: access.error }, { status: access.status });

  const url = new URL(context.request.url);
  const sig = normalizeSig(url.searchParams.get("sig"));
  const id = normalizeSig(url.searchParams.get("id"));
  if (!isValidSig(sig) || !id) {
    return authJson({ ok: false, error: "A play signature and clip id are required." }, { status: 400 });
  }

  const store = getManifestStore(context.env);
  const { entries, legacy: legacyManifest } = await readManifest(store, context.env, access.teamId, sig);
  const target = entries.find((entry) => entry.id === id);
  if (!target) {
    return authJson({ ok: false, error: "Clip not found." }, { status: 404 });
  }

  const remaining = entries.filter((entry) => entry.id !== id);
  await writeTeamClipManifest(store, access.teamId, sig, remaining);

  // Never delete any object reached through a legacy KV manifest. It may be
  // the only recoverable copy while the primary-team migration is incomplete.
  if (!legacyManifest) {
    const bucket = requireClipBucket(context.env);
    await deleteSupersededCanonicalClipObjects(bucket, access.teamId, [target], remaining);
  }

  return authJson({ ok: true, clips: remaining.map(publicClip) });
}

export async function onRequestGet(context) {
  return listClips(context);
}

export async function onRequestPost(context) {
  return uploadClip(context);
}

export async function onRequestDelete(context) {
  return deleteClip(context);
}
